### PR TITLE
Add tests for all supported node versions and update node versions

### PR DESCRIPTION
**Pull request by javoire**
* Test cloud builder against example app
* Remove redundant mocha test
* Update node versions
* Remove node 6 since it's old and requires ES5 syntax in example tests
* freetype and harfbuzz fix for "missing symbols" error in `node:9.11.1-alpine`
* Add Jest example usage to example app

@palmerj3

### CODE REVIEW

**Comment by javoire** [comment]
for reference, here's the "missing symbols" bug https://github.com/GoogleChrome/puppeteer/issues/3019#issuecomment-417227105

**Comment by palmerj3** [comment]
👍

**Comment by palmerj3** [comment]
@ImJasonH if you wouldn't mind reviewing & merging

**Comment by nof20** [comment]
Looks good.  Thanks!

**Pull request merged**
