### PR TITLE
Fix sdkmanager URL and path

### PR DESCRIPTION
**Pull request by Sugihiru**
The Flutter image is currently broken due to the changes in the Android side from `sdk-tools` to `cmdline-tools`, which is known to be a problem Flutter side with `flutter doctor`.
The following problem occurs when using the current `sdk-tools` : 
```
Step #0: Step 23/28 : RUN yes "y" | flutter doctor --android-licenses
Step #0:  ---> Running in 1b6620ba9317
Step #0: [91mAndroid sdkmanager not found. Update to the latest Android SDK and ensure that the cmdline-tools are installed to resolve this.
Step #0: The command '/bin/sh -c yes "y" | flutter doctor --android-licenses' returned a non-zero code: 1
Finished Step #0
ERROR
```

This PR uses `cmdline-tools` and updates the paths accordingly

### CODE REVIEW

**Comment by Sugihiru** [comment]
@googlebot I fixed it.

**Comment by Sese-Schneider** [comment]
@amcooper this is cruicial to fix the flutter cloud builder.
I came across the same issue and luckily this PR fixes it.

**Comment by CriPstian** [comment]
I also confirm this PR fixes the cloud builder. How could we get this into the main repo?

**Comment by amcooper** [comment]
@ronanww ?

**Review by ronanww — APPROVED** [review]

**Pull request merged**
