### PR TITLE
add boot-clj

### PR DESCRIPTION
**Pull request by flyboarder**
Added boot clojure build tool

### CODE REVIEW

**Comment by flyboarder** [comment]
I signed it!

**Comment by nof20** [comment]
Hey, thanks so much for this!  Is there any way you could include a simple example of use too?

**Comment by flyboarder** [comment]
@nof20 I am having trouble getting the `ENTRYPOINT` to run from a cloud builder request. I am following the packer example however once the custom step is built, I cannot pass anything to boot. I am able to run it from the Dockerfile. Any help would be appreciated!

**Comment by flyboarder** [comment]
Here is my error:
`-v: 1: -v: [“/usr/bin/boot”]: not found`

**Comment by flyboarder** [comment]
Correction, I believe this is issue is now resolved. Seems to be due to text encoding.
Correct: `Step #1: Step 11/11 : ENTRYPOINT /usr/bin/boot`
BAD: `Step #1: Step 11/11 : ENTRYPOINT [“/usr/bin/boot”]` (notice the quotes)

This could be documented somewhere as something to lookout for.

**Comment by nof20** [comment]
Hey @flyboarder, looks great!  Could you include an example?  How about something like `boot -h fib.boot` where `fib.boot` is:

```
#!/usr/bin/env boot
 
(defn fib
    ([n]
        (fib [0 1] n))
    ([pair, n]
        (print (first pair) " ")
        (if (> n 0)
            (fib [(second pair) (apply + pair)] (- n 1))
            (println))))

(defn -main [& args]
    (let [limit (first args)]
        (println "Printing fibonacci sequence up to " limit "numbers")
        (fib (Integer/parseInt limit))))
```

(Blatantly ripped off from [Boot: Getting Started With Clojure In < 10 Minutes](https://lionfacelemonface.wordpress.com/2015/01/17/boot-getting-started-with-clojure-in-10-minutes/))

**Comment by jcf** [comment]
Is there interest in adding support for [Leiningen](https://leiningen.org/) too?

@nof20 the example code isn't idiomatic Clojure. There's IO taking place inside the FIbonacci algorithm, and the formatting doesn't adhere to any community standard I'm familiar with.

I don't want to be a pain or start bikeshedding, but maybe something simpler would be good enough?

``` clj
#!/usr/bin/env boot

(defn -main
  []
  (println "Congratulations! You're running Clojure code via Boot."))
```

1. https://github.com/bbatsov/clojure-style-guide
1. https://github.com/metabase/metabase/wiki/Metabase-Clojure-Style-Guide

**Comment by nof20** [comment]
Hey @jcf .  Yes - would love to have Leiningen.

Great feedback on Clojure, thank you.  I'll merge this PR as it stands, and add the much simpler example you proposed.

**Pull request merged**
