### PR TITLE
Add rsync.

### PR DESCRIPTION
**Pull request by ebaskoro**
Added a custom builder that invokes `rsync` tool.

### CODE REVIEW

**Comment by ebaskoro** [comment]
@googlebot I fixed it.

**Comment by sanastos** [comment]
Would you mind adding an example that just rsyncs one file locally that maintainers can use as a sanity check?

Also, minor, but a few of your files are missing trailing newlines.

Other than that, looks good to me.

**Comment by codrienne** [comment]
Ping. Re: sanastos's comment, do you mind adding an example?

**Comment by ebaskoro** [comment]
Sure.

**Comment by codrienne** [comment]
nit: Could you also add a trailing newline to the cloudbuild.yaml and Dockerfile? Once that's added with a simple example, this will be good to merge.

**Comment by ebaskoro** [comment]
@sanastos @codrienne I have addressed your comments. Thanks.

**Comment by codrienne** [comment]
Great, thanks!

**Pull request merged**
