### PR TITLE
State tool

### PR DESCRIPTION
**Pull request by Naatan**
This adds a cloud builder that integrates the [State Tool](https://www.activestate.com/products/platform/state-tool/), which allows you to pull in language runtimes from the [ActiveState Platform](https://www.activestate.com/products/platform/).

### CODE REVIEW

**Comment by codrienne** [comment]
@Naatan I'm reviewing the PRs on the repo. This is an old PR, so I'm going to close it, but feel free to re-open it or file a new PR. It looks like the CLA just wasn't signed, which should be fairly easy to do.

**Comment by Naatan** [comment]
Hi Codrienne, still waiting on legal to get back to me. Will reopen once I have internal approval.

**Comment by codrienne** [comment]
Great, thanks!

**Comment by Naatan** [comment]
I am told the CLA has been signed by legal and my email was added to the group that was shared in the CLA agreement, so in theory we should be good to go.

**Comment by codrienne** [comment]
The CLA is still complaining. I'm guessing the author of some of your commits are not the same as the CLA-approved email you used. Edit the commit authors?

**Comment by Naatan** [comment]
I think it might be because I was showing a different email on github (I had the right one registered, just not displayed). I just switched it, let's see if that does it.

**Comment by Naatan** [comment]
@codrienne can I trigger the cla bot to refresh somehow?

**Comment by LOZORD** [comment]
@Naatan , `@googlebot I signed it!` should retrigger it I think

**Comment by codrienne** [comment]
@Naatan Sorry I missed your question. Thanks for retriggering the CLA check, LOZORD :) LGTM. I'll merge it.

**Pull request merged**
