### PR TITLE
vault builder

### PR DESCRIPTION
**Pull request by arturrez**
vault cloud builder for communication with vault during build process. 
Please refer to Readme.md and examples folder

### CODE REVIEW

**Comment by arturrez** [comment]
@googlebot I signed it!

**Comment by codrienne** [comment]
I know you have it in the README, but can you please add an example subdirectory? 
e.g. https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/terraform

Then it'll be good to merge.

**Comment by arturrez** [comment]
Hello.
I added 2 examples including one as a quick workaround for the lack on letsencrypt CA cert in alpine Linux.
Also bumped vault version from 1.2.2 to 1.2.3 ( latest)

**Comment by codrienne** [comment]
Great, thanks! One more nit:  can you add a trailing newline to the Dockerfile?

**Comment by arturrez** [comment]
sorry, add or remove it?  I am not sure what you mean

**Comment by codrienne** [comment]
Add an empty newline to the end of the Dockerfile and YAML. In the `Files Changed` UI, there's a small red icon at the end of the files complaining about the lack of a newline.

**Comment by arturrez** [comment]
thank you. finally found this setting in vscode:)
fixed and should be good to go

**Comment by codrienne** [comment]
Awesome, thanks!

**Pull request merged**
