### PR TITLE
Fix caching volume issues in Android examples

### PR DESCRIPTION
**Pull request by pavlospt**
There was a wrong path referenced in one sample and on the other the indentation was wrong.

### CODE REVIEW

**Comment by pavlospt** [comment]
Hey @rharter the documentation of Cloud build though suggests that indentation, so that is why I kept it consistent between volume declarations and not among the general indentation of the file! I could revert if it's an issue!

**Comment by rharter** [comment]
I think it makes sense that the examples use the same indentation as the documentation.  I would argue, however, that consistency within files is more important.

With that in mind, I'm not opposed to changing the list indentation style of the file, I just think that if we're going to update the indentation of some lists to match the docs we should update them all.  I would vote for adding the rest of the indentation fixes to this PR.

**Comment by pavlospt** [comment]
Sure that sounds fine! I will update the PR accordingly!

**Comment by pavlospt** [comment]
@rharter I updated the syntax for `waitFor` and fixed any indentation issues I spotted! Let me know if it is ok?

**Comment by rharter** [comment]
@nof20 would love to see this one merged, as well.  Thanks!

**Comment by pavlospt** [comment]
@sanastos would it be possible to take a look at this one as well?

**Comment by leeonlee** [comment]
Looks good to me, thanks!

FYI: Cloud Build now supports global volumes so they only have to be defined once at the build level and they'll be mounted to each step: https://cloud.google.com/cloud-build/docs/api/reference/rest/Shared.Types/Build#BuildOptions

**Comment by pavlospt** [comment]
@leeonlee Great, thanks for sharing this!

**Pull request merged**
