### PR TITLE
Support for Swift build steps.

### PR DESCRIPTION
**Pull request by Andrewangeta**

### CODE REVIEW

**Comment by Andrewangeta** [comment]
@nof20 Bot seems to be down also I've resigned the CLA.

**Comment by Andrewangeta** [comment]
I signed it!

**Comment by nof20** [comment]
This is awesome, thanks so much.  

Can you remove the `.DS_Store` files?  I also notice you're using the `drewskiwin:swift-latest` base image for latest rather than an official one, was there a reason for that?

On the CLA: I checked your details and it looks like `andrewangeta@gmail.com` is properly registered, but you have some commits here from `andrew.edwards@alliancedata.com` which is not.  Quickest way to fix this is to [squash your commits](https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git) using the gmail account - can you do that and let me know?

**Comment by Andrewangeta** [comment]
@nof20 Done :)

**Comment by nof20** [comment]
Perfect, thanks for sticking with it!

**Pull request merged**
