### PR TITLE
added github cli cloudbuilder

### PR DESCRIPTION
**Pull request by petomalina**
This PR adds the new Github cli tool as a builder, allowing us to create comments on PRs and issues easily within builds.

Why I created this?
- I needed a way to post results of the `terraform` into PRs and issues.

I also created an article explaining usage in more detail here: https://petomalina.medium.com/terraform-plan-in-pull-requests-with-gcp-cloud-build-603790a2b734

### CODE REVIEW

**Comment by ipv1337** [comment]
Any movement on this PR? Looks like a nice image to use in our build steps as well.

**Comment by petomalina** [comment]
@ipv1337 this one is done, so unless anybody has review comments, it's ready to be merged. We are using [petomalina/cloud-builders-community](https://github.com/petomalina/cloud-builders-community/tree/add-github-cli) fork for this image until it's merged.

**Review by leeonlee — CHANGES_REQUESTED** [review]
Looks good, let's add newlines to the end of files without them to keep it consistent. I'll merge it in afterwards

**Comment by petomalina** [comment]
@leeonlee all files should now contain newlines at their end

**Review by leeonlee — APPROVED** [review]

**Pull request merged**
