### PR TITLE
[builders/helm] Upgrade helm, add option for helm-diff

### PR DESCRIPTION
**Pull request by naseemkullah**

### CODE REVIEW

**Comment by rimusz** [comment]
Please document `helm-diff` in the readme.

**Comment by nof20** [comment]
@naseemkullah are you able to do that?  Thanks!

**Comment by naseemkullah** [comment]
Hi @nof20,
I've since added a line about helm-diff in the README.md.
Thanks

**Comment by rimusz** [comment]
LGTM

**Comment by nof20** [comment]
Thank you!

**Comment by naseemkullah** [comment]
Thanks!

**Pull request merged**
