### PR TITLE
Add: npm-puppeteer cloud build builder

### PR DESCRIPTION
**Pull request by tomchinery**
Adds npm-puppeteer cloud build builder with 'hello world' example.

### CODE REVIEW

**Comment by tomchinery** [comment]
@googlebot I believe we have signed the CLA.

**Comment by tomchinery** [comment]
I signed it!

**Comment by nof20** [comment]
Sorry @tomchinery , I checked your email, GitHub ID and company name and I can't find any record of a CLA for any of them.  If you think you're covered under a Corporate CLA, please confirm the company details at https://cla.developers.google.com/clas, or arrange to have one signed.  Thanks!

**Comment by tomchinery** [comment]
I signed it!

**Comment by leeonlee** [comment]
Hey Tom,

I'm having trouble running the provided `npm-puppeteer/cloudbuild.yaml`.  Does it work for you?

```
Step #4: Already have image: gcr.io/argo-local-leonlee/npm-puppeteer:node-10.15.3
Step #4:                                                                        
Step #4: > hello_world@0.0.1 test:ci /workspace/examples/hello_world
Step #4: > jest --config=jest-puppeteer.js --runInBand --ci
Step #4:                               
Step #4: FAIL tests/index.test.js
Step #4:   index.js         
Step #4:     ✕ renders / (58ms)
Step #4:                         
Step #4:   ● index.js › renders /
Step #4:                                                                                       
Step #4:     net::ERR_CONNECTION_REFUSED at http://localhost:3000
Step #4:         
Step #4:       4 | describe('index.js', () => {                  
Step #4:       5 |     beforeAll(async () => {                                                             
Step #4:     > 6 |         await page.goto('http://localhost:3000');
Step #4:         |                    ^                      
Step #4:       7 |     });                                                       
Step #4:       8 |
Step #4:       9 |     it('renders /', async () => {
Step #4:                                                                                        
Step #4:       at navigate (node_modules/puppeteer/lib/FrameManager.js:120:37)                                                                                                                                                                                                                          
Step #4:         -- ASYNC --
Step #4:       at Frame.<anonymous> (node_modules/puppeteer/lib/helper.js:111:15)                       
Step #4:       at Page.goto (node_modules/puppeteer/lib/Page.js:674:49)
Step #4:       at Page.<anonymous> (node_modules/puppeteer/lib/helper.js:112:23)                                                                                                                                                                                                                       
Step #4:       at Object.goto (tests/index.test.js:6:20)
Step #4:
Step #4:   ● index.js › renders /
Step #4:
Step #4:     Text not found "Hello World!"
Step #4:
Step #4:       JSHandles can be evaluated only in the context they were created!
Step #4:
Step #4: Test Suites: 1 failed, 1 total
Step #4: Tests:       1 failed, 1 total
Step #4: Snapshots:   0 total
Step #4: Time:        0.793s
Step #4: Ran all test suites.
Step #4: npm ERR! code ELIFECYCLE
Step #4: npm ERR! errno 1
Step #4: npm ERR! hello_world@0.0.1 test:ci: `jest --config=jest-puppeteer.js --runInBand --ci`
Step #4: npm ERR! Exit status 1
Step #4: npm ERR!
Step #4: npm ERR! Failed at the hello_world@0.0.1 test:ci script.
Step #4: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Step #4:
Step #4: npm ERR! A complete log of this run can be found in:
Step #4: npm ERR!     /builder/home/.npm/_logs/2019-09-16T19_51_38_758Z-debug.log
Finished Step #4
```

**Comment by codrienne** [comment]
Following up: can you please address leonlee's comment above? We run the cloudbuild.yaml to make sure it works before merging.

**Comment by codrienne** [comment]
Hi, I'm closing out old PRs on the repo. The action items above have not yet been addressed. Feel free to re-open or file a new PR when the AIs are addressed.

**Pull request closed without merging**
