### PR TITLE
compodoc builder and minor dockerfile cleanup for Sonarqube builder

### PR DESCRIPTION
**Pull request by rprakashg**
Added the compodoc builder and example demonstrating the use 

#190

### CODE REVIEW

**Comment by nof20** [comment]
Hey @rprakashg !  Thanks for submitting this.  It all looks good, except the example build actually fails:

```
Step #1: Caught non-retryable exception while listing gs://compodoc-demo-todomvc-angularjs/: AccessDeniedException: 403 X@cloudbuild.gserviceaccount.com does not have storage.objects.list access to compodoc-demo-todomvc-angularjs.
Step #1: CommandException: Caught non-retryable exception - aborting rsync
Finished Step #1
ERROR
ERROR: build step 1 "gcr.io/cloud-builders/gsutil" failed: exit status 1
```

As you can see, it's because of the last step in `cloudbuild.yaml` which attempts to copy the build documentation to a bucket I don't have access to.  Could you remove this?  Most people looking for example usage will be looking at the logs, which are pretty verbose and helpful.

**Comment by rprakashg** [comment]
Ok done, was just trying to make sure example shows how to push to a storage bucket. Ideally you'd want to do that after generating doc right?

**Comment by rprakashg** [comment]
Hey @nof020 do you need me to do anything else with this PR?

**Comment by nof20** [comment]
Nah all good.  Thanks!

**Pull request merged**
