### PR TITLE
Bump Kustomize version to 3.2.1

### PR DESCRIPTION
**Pull request by fregdee**
## Releases
https://github.com/kubernetes-sigs/kustomize/releases

## Release note
**v3.2.0**: https://github.com/kubernetes-sigs/kustomize/blob/master/docs/v3.2.0.md
**v3.2.1**: https://github.com/kubernetes-sigs/kustomize/blob/master/docs/v3.2.1.md

### CODE REVIEW

**Comment by codrienne** [comment]
I can't build the cloudbuild.yaml with the new version, but when I use the older version, it works. Can you take another look?
```
$ gcloud builds submit --config=kustomize/cloudbuild.yaml .
...logs logs logs...
Step #0: Preparing to unpack .../wget_1.17.1-1ubuntu1.5_amd64.deb ...
Step #0: Unpacking wget (1.17.1-1ubuntu1.5) ...
Step #0: Setting up wget (1.17.1-1ubuntu1.5) ...
Step #0: --2019-10-17 16:16:44--  https://github.com/kubernetes-sigs/kustomize/releases/download/v3.2.1/kustomize_3.2.1_linux_amd64
Step #0: Resolving github.com (github.com)... 192.30.253.112
Step #0: Connecting to github.com (github.com)|192.30.253.112|:443... connected.
Step #0: HTTP request sent, awaiting response... 404 Not Found
Step #0: 2019-10-17 16:16:44 ERROR 404: Not Found.
Step #0: 
Step #0: The command '/bin/sh -c apt-get update &&     apt-get install -y wget &&     wget https://github.com/kubernetes-sigs/kustomize/releases/download/${VERSION}/kustomize_${VER}_linux_amd64 &&     mkdir /builder/kustomize &&     mv kustomize_${VER}_linux_amd64 /builder/kustomize/kustomize &&     chmod +x /builder/kustomize/kustomize &&     chmod +x /builder/kustomize.bash &&     apt-get remove --purge -y wget &&     apt-get --purge -y autoremove &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 8
Finished Step #0
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: exit status 8
Step #0: 
```

**Comment by CharlesWinter** [comment]
Hi guys is there any progress on this. Happy to take a look myself if required.

**Comment by prabenzom** [comment]
Hi, I just tried this as well and am getting the same 404 error as codrienne@

**Comment by robbertkl** [comment]
In the Dockerfile, the wget line needs to be changed to:

```
    wget https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2F${VERSION}/kustomize_kustomize.${VERSION}_linux_amd64 && \
```

This new URL is used for all releases 3.2.1 (see https://github.com/kubernetes-sigs/kustomize/releases/).

**Comment by LOZORD** [comment]
Thanks for your PR! This should no longer be necessary with #324

**Pull request closed without merging**
