### PR TITLE
Add docker executable back in

### LINKED ISSUE #242: `docker-compose` fails on `run` argument.
## Affected builder image

`docker-compose`

## Expected Behavior

docker-compose/README.md states "Arguments passed to this builder will be passed to docker-compose directly, allowing callers to run any docker-compose command."

I would therefore expect running
```
gcloud  builds submit --config=cloudbuild.yaml .
```
on a modified `examples/hello-world/cloudbuild.yaml`:
```
steps:
- name: 'gcr.io/cloud-builders-community/docker-compose'
  args: ['run','helloworld']
```
to output
```
Step #0: Hello world
```

## Actual Behavior

Running
```
gcloud  builds submit --config=cloudbuild.yaml .
```
on the modified `examples/hello-world/cloudbuild.yaml`:
```
steps:
- name: 'gcr.io/cloud-builders-community/docker-compose'
  args: ['run','helloworld']
```
outputs
```
Couldn't find `docker` binary. You might need to install Docker:

https://docs.docker.com/engine/installation/
ERROR
ERROR: build step 0 "gcr.io/overleaf-ops/docker-compose" failed: exit status 1
--------------------------------------------------------------------------------------------------------------------------------

ERROR: (gcloud.builds.submit) build 086991cb-c5f0-47d7-80b1-fd5e39fe4f49 completed with status "FAILURE"
```

## Steps to Reproduce the Problem

Change directory to `docker-compose/examples/hello-world`. Edit the `cloudbuild.yaml` file:
```
steps:
- name: 'gcr.io/cloud-builders-community/docker-compose'
  args: ['run','helloworld']
```
Run
```
gcloud  builds submit --config=cloudbuild.yaml .
```

## Additional Info

The problem can be solved by adding the `docker-ce-cli` package to the `docker-compose` image.

### PR DESCRIPTION
**Pull request by boothead**
Fixes #242

### CODE REVIEW

**Comment by nof20** [comment]
Looks good, thanks!

**Comment by nof20** [comment]
@boothead can you fix the CLA issue above and ping this thread when done?

**Comment by boothead** [comment]
Sure - just need to check with legal at work first.

**Comment by sdiehl** [comment]
The CLA for Adjoint UK Ltd has been added

**Comment by boothead** [comment]
Hi my employer has signed for the company on my behalf. Is that sufficient @nof20?

**Comment by nof20** [comment]
A couple of things:

- I don't see Adjoint UK Ltd in the list of corporate entities yet, which means it's probably somewhere in the pipes with Google legal.  Let's give them a couple of days.
- We then need one consistent email address for Ben in three places:
    * Listed on his GitHub profile
    * Listed in the Google Group used by Adjoint UK Ltd to authorize their contributors
    * Attached to all commits in this PR.  The simplest way to update this is [via git rebase](https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-one-specific-commit).

Thanks for taking the time to work through this.  It's much easier after the first time!

**Comment by boothead** [comment]
@nof20 I've updated my email address on my github profile and in the commit in this PR (also rebased on master), and the CLA has come through. @sdiehl do you know what to change in the google group mentioned?

**Comment by nof20** [comment]
If googlebot says you're all set... you must be in the list.

Thanks again, we're good to go!

**Pull request merged**
